name: TerraformDestroy

on:
  workflow_dispatch:
env:
  BUCKET: anu-batch9
  TFSTATE_FILE: S3.tfstate
  aws_region: ap-south-1

jobs:
    destroy_bucket:
      name: destroy
      runs-on: ubuntu-latest
      steps:
        - name: CheckOut
          uses: actions/checkout@v3
        - name: set up terraform hasicrop
          uses: hashicorp/setup-terraform@v1

        - name: configure aws credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
            aws-region: ${{env.aws_region}}
  
        - name: terraform init
          run: |
            cd modulefile
            terraform init -reconfigure -backend-config="bucket=${{ env.BUCKET }}" -backend-config="key=${{ env.TFSTATE_FILE }}" -backend-config="region=${{ env.aws_region }}"
            
        - name: destroy
          run: |
            cd modulefile
            terraform destroy -auto-approve